# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200)),
                ('organizer', models.CharField(default=b'', max_length=30)),
                ('location', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('time', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('description', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('image', models.CharField(default=b'', max_length=500)),
            ],
        ),
    ]
