# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160414_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='postevent',
            name='time',
        ),
        migrations.AddField(
            model_name='postevent',
            name='event_topic',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='postevent',
            name='event_type',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='postevent',
            name='ticket',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 23, 24, 25, 638098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='image',
            field=models.CharField(default=b'http://weneedfun.com/wp-content/uploads/2016/02/Shanghai-5.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 23, 24, 25, 638048, tzinfo=utc)),
        ),
    ]
