# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20160415_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_topic', models.CharField(default=b'', max_length=200)),
                ('interested_type', models.CharField(default=b'', max_length=200)),
                ('user_image', models.CharField(default=b'', max_length=300)),
                ('user_description', models.CharField(default=b'', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 20, 58, 1, 209809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 20, 58, 1, 209772, tzinfo=utc)),
        ),
    ]
