# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20160416_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_description', models.CharField(default=b'', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_image', models.CharField(default=b'', max_length=300)),
                ('user_description', models.CharField(default=b'', max_length=300)),
                ('knowledge', models.IntegerField()),
                ('friends', models.IntegerField()),
                ('fun', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='postevent',
            name='user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 18, 44, 59, 32388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 18, 44, 59, 32354, tzinfo=utc)),
        ),
    ]
