# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20160417_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 19, 32, 25, 172797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 19, 32, 25, 172762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='fun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='knowledge',
            field=models.IntegerField(default=0),
        ),
    ]
