# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20160417_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='fun',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='attraction',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='concert',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='conference',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='convention',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='expo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='festival',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gala',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='game',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='networking',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='seminar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='social',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='trip',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='workshop',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='description',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 20, 30, 21, 415193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 20, 30, 21, 415161, tzinfo=utc)),
        ),
    ]
