# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20160417_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 22, 34, 517876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 22, 34, 517841, tzinfo=utc)),
        ),
    ]
