# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20160418_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 22, 57, 42, 961139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 22, 57, 42, 961108, tzinfo=utc)),
        ),
    ]
