# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20160418_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSetting',
            new_name='UserInfo',
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 23, 6, 28, 498502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 23, 6, 28, 498469, tzinfo=utc)),
        ),
    ]
