# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20160418_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 2, 16, 37, 715399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 2, 16, 37, 715366, tzinfo=utc)),
        ),
    ]
