# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20160420_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 0, 48, 51, 511789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 0, 48, 51, 511756, tzinfo=utc)),
        ),
    ]
