# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20160426_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 3, 4, 7, 887752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 3, 4, 7, 887719, tzinfo=utc)),
        ),
    ]
