# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20160426_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 13, 45, 17, 782154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 13, 45, 17, 782120, tzinfo=utc)),
        ),
    ]
